### ISSUE TITLE
Add rule for resource missing tags

### ISSUE THREAD

**Issue by guybartal** [terraform-linters/tflint-ruleset-azurerm#193] opened 2022-08-30 15:19 UTC
As a Terraform developer I would like to be noticed when I missed required tags resources
so I won't forget to add those when I add new resources in Terraform module

**Comment by guybartal** [comment] 2022-08-30 15:21
adding this rule with help solve this issue: [https://github.com/orgs/microsoft/projects/232](https://github.com/orgs/microsoft/projects/232)

**Comment by wata727** [comment] 2022-08-30 16:15
Duplicate of https://github.com/terraform-linters/tflint-ruleset-azurerm/issues/133

**Closed by wata727** 2022-08-30 16:15 UTC
