### ISSUE TITLE
Error: fork/exec xxxx.tflint.d/plugins/tflint-ruleset-azurerm: permission denied

### ISSUE THREAD

**Issue by NK74** [terraform-linters/tflint-ruleset-azurerm#101] opened 2021-03-10 19:12 UTC
Hello,

I'm trying to use your plugin but :
Failed to initialize plugins. An error occurred:
Error: fork/exec /Users/myUser/.tflint.d/plugins/tflint-ruleset-azurerm: permission denied

```
❯ TFLINT_LOG=debug tflint
20:10:42 config.go:96: [INFO] Load config: .tflint.hcl
20:10:42 config.go:311: [DEBUG] Config loaded
20:10:42 config.go:312: [DEBUG]   Module: true
20:10:42 config.go:313: [DEBUG]   Force: false
20:10:42 config.go:314: [DEBUG]   IgnoreModules: map[string]bool{}
20:10:42 config.go:315: [DEBUG]   Varfiles: []string{"terraform.tfvars"}
20:10:42 config.go:316: [DEBUG]   Variables: []string{}
20:10:42 config.go:317: [DEBUG]   DisabledByDefault: false
20:10:42 config.go:318: [DEBUG]   Rules: map[string]*tflint.RuleConfig{}
20:10:42 config.go:319: [DEBUG]   Plugins: map[string]*tflint.PluginConfig{"azurerm":(*tflint.PluginConfig)(0xc000546510)}
20:10:42 option.go:49: [DEBUG] CLI Options
20:10:42 option.go:50: [DEBUG]   Module: false
20:10:42 option.go:51: [DEBUG]   Force: false
20:10:42 option.go:52: [DEBUG]   IgnoreModules: map[string]bool{}
20:10:42 option.go:53: [DEBUG]   EnableRules: []string(nil)
20:10:42 option.go:54: [DEBUG]   DisableRules: []string(nil)
20:10:42 option.go:55: [DEBUG]   Only: []string(nil)
20:10:42 option.go:56: [DEBUG]   EnablePlugins: []string(nil)
20:10:42 option.go:57: [DEBUG]   Varfiles: []string{}
20:10:42 option.go:58: [DEBUG]   Variables: []string{}
20:10:42 loader.go:57: [INFO] Initialize new loader
20:10:42 loader.go:82: [INFO] Load configurations under .
20:10:42 loader.go:97: [INFO] Module inspection is enabled. Building a root module with children...
20:10:42 loader.go:170: [INFO] Load values files
20:10:42 loader.go:237: [INFO] Load `terraform.tfvars`
20:10:42 loader.go:237: [INFO] Load `terraform.tfvars`
20:10:42 runner.go:50: [INFO] Initialize new runner for root
20:10:42 discovery.go:68: [INFO] Plugin `azurerm` found
2021-03-10T20:10:42.336+0100 [DEBUG] plugin: starting plugin: path=/Users/MyUser/.tflint.d/plugins/tflint-ruleset-azurerm args=[/Users/MyYser/.tflint.d/plugins/tflint-ruleset-azurerm]
Failed to initialize plugins. An error occurred:

Error: fork/exec /Users/MyUser/.tflint.d/plugins/tflint-ruleset-azurerm: permission denied
```

MacOs (BigSur) with TF v0.13.3 & go1.16 darwin/amd64
Already changed folder/files permissions

Thanks

**Comment by mike-serchenia** [comment] 2021-03-12 12:29
the same story but with 
tflint-ruleset-google

**Comment by mike-serchenia** [comment] 2021-03-12 16:17
@NK74 found it
in my case, I was uploading the plugin to 
`/root/.tflint.d/plugins/tflint-ruleset-google`  after I've changed to `/root/.tflint.d/plugins/` it passed

**Comment by wata727** [comment] 2021-03-14 08:10
Umm... I was unable to reproduce this issue. Below is the environment I have confirmed:

```
$ tflint -v
TFLint version 0.25.0
+ ruleset.azurerm (0.9.0)
```

If you're only having issues with v0.9, it's possible that the update to Go 1.16 is affecting you.
Can you provide a Docker image etc. that can reproduce this problem?

**Comment by krynn1** [comment] 2021-03-16 17:26
I have the same problem but iwth the azure plugin. I am running go version go1.16.1 darwin/amd64

**Comment by mike-serchenia** [comment] 2021-03-16 18:13
@krynn1 upload the pluging in `~/.tflint.d/plugins/`
not in `~/.tflint.d/plugins/tflint-ruleset-google/`

**Comment by krynn1** [comment] 2021-03-18 02:53
> @krynn1 upload the plugin in `~/.tflint.d/plugins/`
> not in `~/.tflint.d/plugins/tflint-ruleset-google/`

I realized I had to make build the plugin. Is there be output if it runs successfully but doesn't find anything?

**Comment by mike-serchenia** [comment] 2021-03-18 09:37
> > @krynn1 upload the plugin in `~/.tflint.d/plugins/`
> > not in `~/.tflint.d/plugins/tflint-ruleset-google/`
> 
> I realized I had to make build the plugin. Is there be output if it runs successfully but doesn't find anything?

No, but you can set log level to debug. You'll see if plugin was found

**Comment by wata727** [comment] 2021-07-23 06:34
We have found that this error occurs if a directory with the same name exists. The bug has been fixed in https://github.com/terraform-linters/tflint/pull/1169.

This issue will be closed, although there may be other causes. If you face a similar issue, open a new issue.

**Closed by wata727** 2021-07-23 06:34 UTC
