### ISSUE TITLE
Failed to check ruleset; Failed to check `azurerm_cosmosdb_account_invalid_name` rule: value has marks, so it cannot be serialized

### ISSUE THREAD

**Issue by tspearconquest** [terraform-linters/tflint-ruleset-azurerm#188] opened 2022-08-12 04:01 UTC
Hello,

I am getting this error when running TFLint v0.35.0 with tflint ruleset azurerm v0.17.1.

Snip of the offending TF code:
```
resource "azurerm_cosmosdb_account" "CLIENTREALM" {
  name                                  = "app-CLIENTREALM-cos-${var.region}"
```

Full error message pasted here to read more easily:
> Failed to check ruleset; Failed to check `azurerm_cosmosdb_account_invalid_name` rule: value has marks, so it cannot be serialized

Please help with a fix

**Comment by wata727** [comment] 2022-08-12 06:13
Duplicate of https://github.com/terraform-linters/tflint/issues/1457

A workaround is to disable the rule or disable the `sensitive` attribute of the `var.region`.

**Comment by tspearconquest** [comment] 2022-08-12 16:22
Thanks, removing sensitive attribute fixed this.

**Closed** 2022-08-12 16:22 UTC
